### ISSUE TITLE
Sprint 2 - Personas defined

### ISSUE THREAD

**Issue by wasimk2651** [wasimk2651/wasim-cw#13]

**Comment by Ddang168** [comment]
[Persona Pelumi.docx](https://zube.io/files/se1/3e1e6c16897ea9e0807d85bbc3af1645-persona-pelumi.docx)[Persona Christina Chan.docx](https://zube.io/files/se1/02bc3b011a9dce8ebf0151b0c9ccb2d0-persona-christina-chan.docx)

**Comment by wasimk2651** [comment]
nice personas. upload as a PDF

**Comment by Ddang168** [comment]
[Persona Pelumi.pdf](https://zube.io/files/se1/076a9a2b124a7b9177de813d58b07cfd-persona-pelumi.pdf)
[Persona Christina Chan.pdf](https://zube.io/files/se1/1d7d6ad16dad7b469816ee249ee46848-persona-christina-chan.pdf)
