### ISSUE TITLE
Sprint 2 - Full use cases defined

### ISSUE THREAD

**Issue by wasimk2651** [wasimk2651/wasim-cw#14]

**Comment by Ddang168** [comment]
[UseCase 1.doc](https://zube.io/files/se1/c63c50875c0006a49b97315013993afa-usecase-1.doc)
[Use Case No 2.docx](https://zube.io/files/se1/362e1a37e9c282688acfe489f98fccb2-use-case-no-2.docx)
[Use Case No 3.docx](https://zube.io/files/se1/7131be0cf698f9d2d50e6f477dc946a4-use-case-no-3.docx)


[Use Case No 1.pdf](https://zube.io/files/se1/e6d5968ed41e65dec133a6d5b0ef700c-use-case-no-1.pdf)
[UseCase 2.pdf](https://zube.io/files/se1/dd8ad8eadd7f94b4d99b2dea7a08c0df-usecase-2.pdf)
[Use Case No 3.pdf](https://zube.io/files/se1/1ff28bbbb326d1c505c82b2d116f6e5d-use-case-no-3.pdf)
