### ISSUE TITLE
Sprint 2 - webpage designs (wireframes)

### ISSUE THREAD

**Issue by wasimk2651** [wasimk2651/wasim-cw#37]
Rough designs of the screens (pages) that your application will have and how these flow together. We are looking for wireframes and a high-level overview of how the application flows together.

**Comment by Dalla1011** [comment]
![wireframe main page SE @2x.png](https://zube.io/files/se1/2ea79a86de460169d5fc27fd93cab979-wireframe-main-page-se-2x.png)
![Login Page Wireframe@2x.png](https://zube.io/files/se1/644f704276d10b272c573ebb539a11b9-login-page-wireframe2x.png)!
![Wireframe Location Page SE@2x.png](https://zube.io/files/se1/9962214bb9be7c986da911c9a6c93490-wireframe-location-page-se2x.png)![COMING SOON PAGE@2x.png](https://zube.io/files/se1/98527829b510ff411efc0ac595d8e121-coming-soon-page2x.png)
