### ISSUE TITLE
Sprint 2 - Tasks defined as user stories

### ISSUE THREAD

**Issue by wasimk2651** [wasimk2651/wasim-cw#9]

**Comment by Dalla1011** [comment]
[user stories.pdf](https://zube.io/files/se1/55041b1ef7cdbfe43858aa91dcf7a5aa-user-stories.pdf)

**Comment by wasimk2651** [comment]
incomplete. complete it and upload as pdf

**Comment by Dalla1011** [comment]
[user stories 2.pdf](https://zube.io/files/se1/958f4571559812047feb9be8e81cada9-user-stories-2.pdf)
